# Numpy Tutorials
- Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python

## Difference between Array and List
- An array can only save values of the same data type, while Lists can save data of different data types.

In [9]:
import numpy as np

In [15]:
my_list = [1,2,3,4]

## Converting a List to Array using numpy
arr = np.array(my_list)

In [17]:
type(arr)

numpy.ndarray

In [19]:
print(arr)

[1 2 3 4]


In [21]:
arr

array([1, 2, 3, 4])

In [31]:
## Check the dimension of the array 
arr.shape

(4,)

In [33]:
## Creating a multidimensional array 

my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,10]
my_lst3 = [11,12,13,14,15]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [35]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [39]:
## First shows the rows and then the columns, row * column = elements in the array
arr.shape


(3, 5)

In [41]:
## Reshaping the array will not change the elements in the array 
arr.reshape(5,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

## Indexing 

In [44]:
## Accessing the array elements
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [59]:
arr[0]

array([1, 2, 3, 4, 5])

In [61]:
arr[1][1]

7

In [67]:
## Selecting Specific rows and columns in Array

arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [69]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [75]:
arr[1:,2:4]

array([[ 8,  9],
       [13, 14]])

In [77]:
arr[1:,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [85]:
## Using arange() to create arrays automatically within a range 

arr = np.arange(0,10)

In [87]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
## Using arange() to create arrays automatically within a range and use step parameter to specify gap

arr = np.arange(0,10, step=2)

In [91]:
arr

array([0, 2, 4, 6, 8])

In [93]:
## linspace() using in Deep Learning 
np.linspace(0,10,num=50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [95]:
## Copying Elements within an Array 

arr = np.array([1,2,3,4,5,6,7,8,9])

In [97]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
# Copy() function and broadcasting
arr[2:]= 100

In [105]:
arr

array([  1,   2, 100, 100, 100, 100, 100, 100, 100])

In [115]:
#Copying array elements to another array 

#referencing is used, not copied
arr1 = arr

In [117]:
arr1[3:]=200

In [119]:
arr1

array([  1,   2, 100, 200, 200, 200, 200, 200, 200])

In [121]:
arr

array([  1,   2, 100, 200, 200, 200, 200, 200, 200])

In [123]:
arr1=arr.copy()

In [125]:
arr1

array([  1,   2, 100, 200, 200, 200, 200, 200, 200])

In [131]:
arr1[3:]=900

In [133]:
arr1

array([  1,   2, 100, 900, 900, 900, 900, 900, 900])

In [135]:
arr

array([  1,   2, 100, 200, 200, 200, 200, 200, 200])

In [139]:
# Some Conditions Used in Exploratory Data Analysis 

val = 2 
# Checks each element in the array if it is less than 'val' value
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [143]:
# all elements are multiplied by 2
arr*2

array([  2,   4, 200, 400, 400, 400, 400, 400, 400])

In [145]:
# Get values of boolean operations not true or false but actual value 

arr[arr<2]

array([1])

In [149]:
# ones() function makes all the elements in the array as 1s 

np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [153]:
# ones() function makes all the elements in the array as 1s. creating with rows and columns

np.ones((2,4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [157]:
## random distribution only gives values greater than 0 and less than 1
np.random.rand(3,4)

array([[0.88038529, 0.85339995, 0.87422681, 0.29476895],
       [0.92817954, 0.38347487, 0.24732557, 0.50277496],
       [0.71625924, 0.53610593, 0.8501741 , 0.79961532]])

In [163]:
arr_exp = np.random.randn(4,4)

In [165]:
arr_exp

array([[ 1.60466514, -0.04772882, -0.08073285, -0.61232225],
       [ 0.15733496,  0.20838359,  2.30193269,  0.5013279 ],
       [ 0.21369866, -1.69048852,  1.55474182,  0.27067413],
       [-1.09666917,  2.36559048,  1.37273973,  0.25790977]])

In [171]:
# Generating random values in int. 3rd parameter is number of elements you want to get 
#between the range 
np.random.randint(0,200,10).reshape(2,5)

array([[186,   3,  76, 193, 113],
       [111,  66,  49, 148, 113]])